# Generated by Django 3.2.20 on 2023-08-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_loan_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
    ]
