# Generated by Django 3.2.20 on 2023-08-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_loan_is_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
